# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  BurakWindows



variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # PowerShell script to download a GitHub repository and clean the current directory
      
      # Specify the GitHub repository URL
      $repoUrl = "https://github.com/akdoganburak/WebGoat.NET.git"
      
      
      
      # Clean current directory before downloading
      Write-Host "Clean current directory before downloading"
      Remove-Item -Path .\* -Force -Recurse

      
      # Download the GitHub repository
      Write-Host "Download the GitHub repository"
      git clone $repoUrl

    
- task: NuGetToolInstaller@1

- checkout: none

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: FortifySCA@7
  inputs:
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    fortifyBuildId: 'webgoat-test'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'LocalScan'
    additionalScanParams: 'msbuild'
    runFortifyUpload: true
    fortifyServerName: 'SSC'
    fortifyApplicationName: 'webgoat'
    fortifyApplicationVersion: 'net'


