# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 none

pool:
  BurakWindows

steps:
- checkout: none

- task: FortifySCA@7
  inputs:
    licenseFile: 'C:\Program Files\Fortify\Fortify_SCA_23.1.1\fortify.license'
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    buildAnalyzerParams: 'msbuild'
    fortifyBuildId: 'azuretest'
    fortifyScanType: 'LocalScan'
